name: Trigger Pipeline on Folder Change

on:
  push:
    branches:
      - main

jobs:
  check-folder-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine Changed Folders
      id: changed_folders
      run: |
        changed_folders=()
        while IFS= read -r line; do
          # Extract the folder path from the diff
          folder=$(echo "$line" | cut -d/ -f1)
          if [ -n "$folder" ] && [ "$folder" != "." ]; then
            changed_folders+=("$folder")
          fi
        done < <(git diff --name-only HEAD^ HEAD)

        # Deduplicate the array of changed folders
        unique_changed_folders=($(echo "${changed_folders[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

